SAP/ui5-tooling-extensions

- .github/workflows/release-please.yml
Activates the npm publish.
Pre-Conditions:
> ci(release-please): activate npm publish by removing dry-run argument

- .github/workflows/release-please.yml
- .npmrc
Adds the auth config to the package and not on the root level.
> ci(release-please): add auth info to package specific npm config

- .github/workflows/fosstars-project-report.yml
With https://github.com/SAP/fosstars-rating-core-action/releases/tag/v1.11.0 it is possible to specify a dedicated git committer.
In the past I thought using a custom token would do the job but thats only the case when the github API is used inside the action. Thats not the case for fosstars so token can be reset to the default github token.
> ci(fosstars): use new git user options and default gh token

- packages/middleware-code-coverage/lib/middleware.js
- packages/middleware-code-coverage/test/unit/lib/middleware.js
This change ensures that the correct package.json is read to determine
the middleware version.
Previously the package.json relative to the `cwd` was used.
Reading the version is only needed once per instance, not per request.
> fix(middleware-code-coverage): fix ping endpoint middleware version

- package-lock.json
- packages/middleware-code-coverage/package.json
Reverts SAP/ui5-tooling-extensions#72
Reverting this PR to submit it again with the correct type `fix`, so that a patch release is created.
> Revert "build(deps): bump xml2js from 0.4.23 to 0.5.0"

- packages/middleware-code-coverage/lib/util.js
- packages/middleware-code-coverage/test/unit/lib/util.js
The middleware collects and merges coverage exclude patterns from the .library files of all reachable library projects. If an exclude pattern is marked with `external="true"`, it should be ignored by the merge as such excludes are only intended for a library local instrumentation.
> fix(middleware-code-coverage): ignore excludes marked as 'external'

- .github/workflows/test.yml
Test execution fails for node v19 because of ava (https://github.com/avajs/ava/pull/3193).
node v20 is the new current version and runs fine.
> ci(test): use latest node version 20

- .github/workflows/test.yml
`macos-13` is available https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/
> ci(test.yml): use macos-13

- packages/middleware-code-coverage/README.md
As middleware-code-coverage is available in the default branch of the openui5 sample app with https://github.com/SAP/openui5-sample-app/commit/1ee9651f568ad280a5aba4aa7b7fea814ce24557 adjusting the documentation here.
> docs(readme.md): use default branch of sample app

- .commitlintrc.json
- .github/dependabot.yml
`release-please` creates a release PR when the commit message starts with "feat", "fix" or "deps". See https://github.com/googleapis/release-please/blob/bdd9b0158ce79d958da01ebf54cb6b07925bc125/README.md?plain=1#L145
> ci(dependabot): use 'deps' for commit message header for deps updates

- release-please-config.json
With https://github.com/SAP/ui5-tooling-extensions/pull/116 we have enabled `deps` as a valid commit message scope but `release-please` requires separate config.
See https://github.com/google-github-actions/release-please-action/issues/804
> ci(release-please): activate release-please for 'deps' commits

- .commitlintrc.json
- release-please-config.json
Allow usage of `revert` scope.
Example:
````
revert: "fix(moduleA): use optionB"
Refs: 676104e, a215868
````
> build: allow commit messages with scope 'revert' for reverts

- .github/workflows/test.yml
This fix is needed in order to be able to have green tests. Currently Node.js v20.6 (which is the most recent one) has some issues with babel and esmock fails.
> fix(infra): downgrade to node v20.5.x

- packages/middleware-code-coverage/README.md
- packages/middleware-code-coverage/docs/API.md
- packages/middleware-code-coverage/lib/coverage-reporter.js
- packages/middleware-code-coverage/test/unit/lib/coverage-reporter.js
This feature enables the extension of default or ui5.yaml's Istanbul configuration, so that certain settings could be adjusted from the frontend.
JIRA: CPOUI5FOUNDATION-709
> feat(middleware-code-coverage): allow coverage watermarks configuration via frontend

- packages/middleware-code-coverage/lib/util.js
> fix(middleware-code-coverage): incomplete string escaping or encoding

- .github/workflows/release-please.yml
Matrix config throws an error when an empty array is used. Therefore add a check for that case.
See https://github.com/SAP/ui5-tooling-extensions/actions/runs/8174526140
> ci(release-please): add check for empty 'paths_released' value

- .commitlintrc.mjs
Release commit contains module name `release: middleware-code-coverage v1.0.0`. Therefore exclusion has to be adjusted.
> ci(commitlint): Fix exclusion for release commit

- .licensee.json
All three packages are licensed under the MIT license, but the package.json file is missing the license field.
PRs to add the license field have already been opened for all three packages.
Follow-Up of https://github.com/SAP/ui5-cli/pull/730/
> build(licensee): Add exception for new deps

- .github/workflows/github-ci.yml
- .github/workflows/issues.yml
- .github/workflows/release-please.yml
- .github/workflows/reuse-compliance.yml
- .github/workflows/test.yml
- Uses latest OS (macos, ubuntu and windows)
- Upgrade Node.js to current active version 22
**Note**: Default test execution still uses Node.js v20.11.0 because it is the minimal required Node.js version for this package
> ci: Upgrade used OS and Node versions

- .github/workflows/release-please.yml
GitHub action "google-github-actions/release-please-action" is deprecated in favor of "googleapis/release-please-action"
See https://github.com/googleapis/release-please-action
> ci(release-please): Migrate to googleapis/release-please-action
